-- Renomeia somente objetos fisicos do banco, preservando dados e contratos da API.
ALTER TABLE "users" RENAME TO "usuarios";
ALTER TABLE "clients" RENAME TO "clientes";
ALTER TABLE "clientContacts" RENAME TO "contatos_clientes";
ALTER TABLE "categories" RENAME TO "categorias";
ALTER TABLE "tags" RENAME TO "etiquetas";
ALTER TABLE "clientTags" RENAME TO "clientes_etiquetas";
ALTER TABLE "schedules" RENAME TO "compromissos";
ALTER TABLE "taskColumns" RENAME TO "colunas_tarefas";
ALTER TABLE "tasks" RENAME TO "tarefas";
ALTER TABLE "notes" RENAME TO "observacoes";
ALTER TABLE "reminders" RENAME TO "lembretes";
ALTER TABLE "attachments" RENAME TO "anexos";
ALTER TABLE "auditLogs" RENAME TO "registros_auditoria";
ALTER TABLE "refreshTokens" RENAME TO "tokens_renovacao";

ALTER TABLE "usuarios" RENAME CONSTRAINT "users_pkey" TO "usuarios_pkey";
ALTER TABLE "clientes" RENAME CONSTRAINT "clients_pkey" TO "clientes_pkey";
ALTER TABLE "contatos_clientes" RENAME CONSTRAINT "clientContacts_pkey" TO "contatos_clientes_pkey";
ALTER TABLE "categorias" RENAME CONSTRAINT "categories_pkey" TO "categorias_pkey";
ALTER TABLE "etiquetas" RENAME CONSTRAINT "tags_pkey" TO "etiquetas_pkey";
ALTER TABLE "clientes_etiquetas" RENAME CONSTRAINT "clientTags_pkey" TO "clientes_etiquetas_pkey";
ALTER TABLE "compromissos" RENAME CONSTRAINT "schedules_pkey" TO "compromissos_pkey";
ALTER TABLE "colunas_tarefas" RENAME CONSTRAINT "taskColumns_pkey" TO "colunas_tarefas_pkey";
ALTER TABLE "tarefas" RENAME CONSTRAINT "tasks_pkey" TO "tarefas_pkey";
ALTER TABLE "observacoes" RENAME CONSTRAINT "notes_pkey" TO "observacoes_pkey";
ALTER TABLE "lembretes" RENAME CONSTRAINT "reminders_pkey" TO "lembretes_pkey";
ALTER TABLE "anexos" RENAME CONSTRAINT "attachments_pkey" TO "anexos_pkey";
ALTER TABLE "registros_auditoria" RENAME CONSTRAINT "auditLogs_pkey" TO "registros_auditoria_pkey";
ALTER TABLE "tokens_renovacao" RENAME CONSTRAINT "refreshTokens_pkey" TO "tokens_renovacao_pkey";

ALTER INDEX "users_email_key" RENAME TO "usuarios_email_key";
ALTER INDEX "clients_document_key" RENAME TO "clientes_document_key";
ALTER INDEX "clients_ownerId_status_idx" RENAME TO "clientes_ownerId_status_idx";
ALTER INDEX "clients_ownerId_name_idx" RENAME TO "clientes_ownerId_name_idx";
ALTER INDEX "clientContacts_clientId_idx" RENAME TO "contatos_clientes_clientId_idx";
ALTER INDEX "categories_name_key" RENAME TO "categorias_name_key";
ALTER INDEX "tags_name_key" RENAME TO "etiquetas_name_key";
ALTER INDEX "schedules_userId_startAt_idx" RENAME TO "compromissos_userId_startAt_idx";
ALTER INDEX "schedules_clientId_idx" RENAME TO "compromissos_clientId_idx";
ALTER INDEX "taskColumns_status_key" RENAME TO "colunas_tarefas_status_key";
ALTER INDEX "tasks_userId_status_idx" RENAME TO "tarefas_userId_status_idx";
ALTER INDEX "tasks_dueDate_idx" RENAME TO "tarefas_dueDate_idx";
ALTER INDEX "notes_clientId_createdAt_idx" RENAME TO "observacoes_clientId_createdAt_idx";
ALTER INDEX "reminders_remindAt_idx" RENAME TO "lembretes_remindAt_idx";
ALTER INDEX "attachments_clientId_idx" RENAME TO "anexos_clientId_idx";
ALTER INDEX "auditLogs_clientId_createdAt_idx" RENAME TO "registros_auditoria_clientId_createdAt_idx";
ALTER INDEX "auditLogs_entity_entityId_idx" RENAME TO "registros_auditoria_entity_entityId_idx";
ALTER INDEX "refreshTokens_tokenHash_key" RENAME TO "tokens_renovacao_tokenHash_key";
ALTER INDEX "refreshTokens_userId_idx" RENAME TO "tokens_renovacao_userId_idx";

ALTER TABLE "clientes" RENAME CONSTRAINT "clients_ownerId_fkey" TO "clientes_ownerId_fkey";
ALTER TABLE "clientes" RENAME CONSTRAINT "clients_categoryId_fkey" TO "clientes_categoryId_fkey";
ALTER TABLE "contatos_clientes" RENAME CONSTRAINT "clientContacts_clientId_fkey" TO "contatos_clientes_clientId_fkey";
ALTER TABLE "clientes_etiquetas" RENAME CONSTRAINT "clientTags_clientId_fkey" TO "clientes_etiquetas_clientId_fkey";
ALTER TABLE "clientes_etiquetas" RENAME CONSTRAINT "clientTags_tagId_fkey" TO "clientes_etiquetas_tagId_fkey";
ALTER TABLE "compromissos" RENAME CONSTRAINT "schedules_userId_fkey" TO "compromissos_userId_fkey";
ALTER TABLE "compromissos" RENAME CONSTRAINT "schedules_clientId_fkey" TO "compromissos_clientId_fkey";
ALTER TABLE "compromissos" RENAME CONSTRAINT "schedules_categoryId_fkey" TO "compromissos_categoryId_fkey";
ALTER TABLE "tarefas" RENAME CONSTRAINT "tasks_userId_fkey" TO "tarefas_userId_fkey";
ALTER TABLE "tarefas" RENAME CONSTRAINT "tasks_clientId_fkey" TO "tarefas_clientId_fkey";
ALTER TABLE "tarefas" RENAME CONSTRAINT "tasks_categoryId_fkey" TO "tarefas_categoryId_fkey";
ALTER TABLE "tarefas" RENAME CONSTRAINT "tasks_columnId_fkey" TO "tarefas_columnId_fkey";
ALTER TABLE "observacoes" RENAME CONSTRAINT "notes_userId_fkey" TO "observacoes_userId_fkey";
ALTER TABLE "observacoes" RENAME CONSTRAINT "notes_clientId_fkey" TO "observacoes_clientId_fkey";
ALTER TABLE "lembretes" RENAME CONSTRAINT "reminders_scheduleId_fkey" TO "lembretes_scheduleId_fkey";
ALTER TABLE "anexos" RENAME CONSTRAINT "attachments_userId_fkey" TO "anexos_userId_fkey";
ALTER TABLE "anexos" RENAME CONSTRAINT "attachments_clientId_fkey" TO "anexos_clientId_fkey";
ALTER TABLE "registros_auditoria" RENAME CONSTRAINT "auditLogs_userId_fkey" TO "registros_auditoria_userId_fkey";
ALTER TABLE "registros_auditoria" RENAME CONSTRAINT "auditLogs_clientId_fkey" TO "registros_auditoria_clientId_fkey";
ALTER TABLE "tokens_renovacao" RENAME CONSTRAINT "refreshTokens_userId_fkey" TO "tokens_renovacao_userId_fkey";
