FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY backend/package.json backend/package.json

RUN npm ci

COPY backend backend

ENV DATABASE_URL=postgresql://u:p@localhost:5432/db
RUN npm run prisma:generate -w backend
RUN npm run build -w backend

EXPOSE 3333

CMD ["npm", "run", "start", "-w", "backend"]
